---
apiVersion: "cluster.kurl.sh/v1beta1"
kind: "Installer"
metadata:
  name: "cicd-demo"
spec:
  kubernetes:
    version: "latest"
  weave:
    version: "latest"
  contour:
    version: "latest"
  registry:
    version: "latest"
  containerd:
    version: "latest"
  kotsadm:
    version: "latest"
  ekco:
    version: "latest"
  minio:
    version: "latest"
  openebs:
    version: "latest"
