---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: guestbook
  name: redis-main
  labels:
    app: redis
spec:
  selector:
    matchLabels:
      app: redis
      role: main
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
        role: main
        tier: backend
    spec:
      containers:
      - name: main
        image: redis
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  namespace: guestbook
  name: redis-main
  labels:
    app: redis
    role: main
    tier: backend
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis
    role: main
    tier: backend
