---
apiVersion: kots.io/v1beta1
kind: Application
metadata:
  name: cicd-demo
spec:
  title: CICD Demo
  icon: https://raw.githubusercontent.com/cncf/artwork/master/projects/kubernetes/icon/color/kubernetes-icon-color.png
  statusInformers:
    - deployment/frontend
    - deployment/redis-master
  ports:
    - serviceName: "example-nginx"
      servicePort: 80
      localPort: 8888
      applicationUrl: "http://example-nginx"
